- name: Create multiple read-only directories
  hosts: all
  become: yes
  become_user: root
  gather_facts: false

  vars:
    base_dir: /opt/awx_test_dirs
    subdirs:
      - dir1
      - dir2
      - dir3

  tasks:
    - name: Create base directory
      file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'

    - name: Create read-only subdirectories
      file:
        path: "{{ base_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ subdirs }}"
